#!/bin/bash

echo "  (tag: 0.1.0)||initial commit"
echo ""
echo "||Bugfix: first bugfix"
echo ""
echo "  (tag: 0.2.0)||first Bugfix"
echo ""
echo "||Feature: first feature"
echo ""
echo "(HEAD -> master)||Changes for feature #123"
echo ""
echo "Bugfix: second bugfix"
echo "Feature: second feature"
echo "Bugfix: third bugfix"
echo ""